swagger: '2.0'
info:
  version: '1.0'
  title: "esameGennaio"
  description: "ciccio"
  license: 
    name: EsameGennaio
    url: https://github.com/pozzobonf98/esamegennaio.git
  contact:
    email: francesco.pozzobon@studenti.unitn.it
host: esamegennaio.herokuapp.com
basePath: /
tags: 
- name: "AREA"

schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /getArea:
    get:
      tags:
      - "Area"
      summary: "Calcolare un'area "
      description: "Calcolare l'area date le risorse nell'url"
      operationId: "calculateArea"
      parameters:
      - in: "body"
        name: "body"
        description: "Calcolare area"
        required: true
        schema:
          $ref: "#/definitions/area"
          
      responses:
        200:
          description: "result= smt"
        400:
          description: "result= -1" 
    
        
  
definitions:

  area:
    type: "object"
    xml:
      name: "Area"